### ISSUE TITLE
Documentation - What is the value in <link>

### ISSUE THREAD

**Issue by cakriwut** [remote-android/redroid-modules#11]
Hi, 
first thanks for this great works. I reading the documentation, and I confused if I need to replace  ```<link>``` in following instruction

-- from README.md

`docker run --rm --cap-add CAP_SYS_MODULE --entrypoint /bin/bash NODE_OS -c "`curl -s <link>`"
 for example, if you are running under ubuntu 18.04, please change NODE_OS to *ubuntu:18.04*`

-- end

Thanks for the explaination.

**Comment by zhouziyang** [comment]
This repo is not maintained recently. And strongly recommend to use the kernel with `binderfs` supported.

**Comment by mhoeben** [comment]
I have been trying to get Redroid working on Amazon Linux, so it can run on g4ad instances. The instructions in this repositrory say I should build from source, but here you recommend to a the kernel with binderfs supported. Are there any instructions how to install the kernel modules on Amazon Linux? I have been searching but I can't find any package mention them.

Thanks in advance, any help is appreciated.
