### ISSUE TITLE
Recommendation for installing kernel modules on Amazon Linux 2023

### ISSUE THREAD

**Issue by mhoeben** [remote-android/redroid-modules#12]
Following the instructions in this repository for Amazon Linux 2, I run into compilation issues for Amazon Linux 2023:
```
git checkout origin/amazonlinux2
sudo yum install git kmod make "kernel-devel-uname-r == `uname -r`"
sudo make # build kernel modules
sudo make install # build and install *unsigned* kernel modules
```
The issues revolve around the kernel functions having different prototypes than the code expects.

In #11 I read that this repository should be considered obsolete and I should be using binderfs and ashmem available in the distribution. I have been searching what package they should be in for Amazon Linux 2023, but so far have not found the package name.

Can you give a suggestion? Any help is appreciated. Thanks in advance.

**Comment by zhouziyang** [comment]
For kernel above `5.7`, extra work (check #4) needed to make out of tree `binderfs` module working.

For running `redroid`, I strongly recommend to use some Linux distros with `binderfs` support (such as `Ubuntu`, although extra packages needed).
