### ISSUE TITLE
/dev/tty: No such device or address

### ISSUE THREAD

**Issue by xxlovex** [remote-android/redroid-modules#13]
I am compiling the kernel based on someone else's documentation, and I have added binder configuration to update the compiled kernel into the system, but I still do not have binder_linux.I have tried to locate these files, and the files displayed are as follows:

root@armbian:~# find / -name binder*
/usr/src/linux-headers-5.15.139-lover/include/uapi/linux/android/binderfs.h
/usr/src/linux-headers-5.15.139-lover/include/uapi/linux/android/binder.h
/usr/include/linux/android/binderfs.h
/usr/include/linux/android/binder.h
/usr/include/c++/11/backward/binders.h

I tried to start redroid-docker with this command, and it displayed a successful start, but docker logs reported this error:
/system/bin/sh: No controlling tty: open /dev/tty: No such device or address
/system/bin/sh: warning: won't have full job control
Did I fail to compile the kernel?Or do I need to perform a secondary compilation based on the files I found?.Thank you!

**Comment by zhouziyang** [comment]
The in-tree `binderfs` is recommended.
And, please file issues in https://github.com/remote-android/redroid-doc
