### ISSUE TITLE
make failed.   

### ISSUE THREAD

**Issue by zhaojinzhou** [remote-android/redroid-modules#2]
Linux instance-20210623-1607 5.8.0-1033-oracle #34~20.04.1-Ubuntu SMP Thu Jun 17 17:27:24 UTC 2021 aarch64 aarch64 aarch64 GNU/Linux

root@instance-20210623-1607:~/redroid-modules# make
make -C ashmem
make[1]: Entering directory '/root/redroid-modules/ashmem'
make -C /lib/modules/`uname -r`/build M=$PWD
make[2]: Entering directory '/usr/src/linux-headers-5.8.0-1033-oracle'
  MODPOST /root/redroid-modules/ashmem/Module.symvers
ERROR: modpost: "kallsyms_lookup_name" [/root/redroid-modules/ashmem/ashmem_linux.ko] undefined!
make[3]: *** [scripts/Makefile.modpost:111: /root/redroid-modules/ashmem/Module.symvers] Error 1
make[3]: *** Deleting file '/root/redroid-modules/ashmem/Module.symvers'
make[2]: *** [Makefile:1698: modules] Error 2
make[2]: Leaving directory '/usr/src/linux-headers-5.8.0-1033-oracle'
make[1]: *** [Makefile:11: all] Error 2
make[1]: Leaving directory '/root/redroid-modules/ashmem'
make: *** [Makefile:8: ashmem] Error 2

**Comment by zhouziyang** [comment]
for 5.7+ kernel, `kallsyms_lookup_name` may not allow to use anymore.

For Ubuntu OS, you can run `modprobe ashmem_linux` and `modprobe binder_linux devices=binder,hwbinder,vndbinder` to install required kernel modules.

**Comment by zhaojinzhou** [comment]
modprobe: FATAL: Module ashmem_linux not found in directory /lib/modules/5.8.0-1033-oracle

any idea?

**Comment by zhouziyang** [comment]
these modules seems not built in this customized Ubuntu. 
try different Ubuntu version? or build kernel by yourself
