### ISSUE TITLE
workaround for 5.7+ kernels (`kallsyms_lookup_name` not exported any more)

### ISSUE THREAD

**Issue by zhouziyang** [remote-android/redroid-modules#4]
https://github.com/zizzu0/LinuxKernelModules/blob/main/FindKallsymsLookupName.c

**Comment by JayDoubleu** [comment]
This seems to be now fixed via fork : https://github.com/choff/anbox-modules

**Comment by tonykcn** [comment]
Hi @zhouziyang ,  has this issue been resolved?  
Most of the current popular kernels are 5.7+, and this "redroid-modules" can't be installed if this issue can't be resolved. 

Any suggestions on how to resolve this issue will be appreciated.
Thanks.

**Comment by zhouziyang** [comment]
please check links above, you can solve via `kprobe`. please be noted that these modules depend on unstable kernel APIs, and you may need adjust for different kernel versions.
BTW, some OS (`ubuntu 20.04+` etc.) already bundle these modules; and some OS (`aliyun linux` etc.) allow modules to link against `kallsyms_lookup_name`.

**Comment by zhouziyang** [comment]
Strongly suggest to use Linux distros with built-in `binderfs` support. The out of tree `binderfs` module possible not stable, and might need much extra work to compatible with the running Linux kernel.

NO plan to fix this issue here.
