### ISSUE TITLE
Can kernel modules installed in container ?

### ISSUE THREAD

**Issue by zhaojinzhou** [remote-android/redroid-modules#8]
I don't have a root priority in the host machine.
Can all these required modules install in docker container?

**Comment by zhouziyang** [comment]
You can install in a privileged container. Or add related CAP to your container

Sent from my iPhone

On Jun 30, 2022, at 1:00 PM, zhaojinzhou ***@***.***> wrote:

﻿

I don't have a root priority in the host machine.
Can all these required modules install in docker container?
